server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: longwu
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  application:
    name: user-service

mybatis:
  type-aliases-package: com.leyou.userservice.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20086/eureka
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.0.1
