server:
  port: 8080
spring:
  application:
    name: user-consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20086/eureka
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule